defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    sampler:
      seed: 123
    storage: null
    study_name: route-search-space
    n_trials: 40
    n_jobs: 1

initial_temperature: 100
cooling_factor:
stopping_temperature: 0.001
chain_length:
map_size:
