defaults:
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    storage: null
    study_name: route-search-space
    n_trials: 100
    n_jobs: 1
    params:
      initial_temperature: interval(500.0, 1500.0)
      cooling_factor: interval(0.8, 0.99)

initial_temperature: 1000.0
cooling_factor: 0.995
stopping_temperature: 0.1
chain_length: 1000
